### ISSUE TITLE
What language do we use?

### ISSUE THREAD

**Issue by larongbingo** [team-noob-noob/libman#12]
We need to finalize the language and frameworks that we will use.

**Comment by joshybara** [comment]
question, would you guys want to make this a PWA?

**Comment by larongbingo** [comment]
But what language would we use to create the Web App? What language would we also use for the Web APIs?

**Comment by joshybara** [comment]
Since Im not that inclined in web dev yet, I guess you have the cue on this one so we leave the decision to you @larongbingo . Hows that sound @BernabePosadas?

**Comment by BernabePosadas** [comment]
> 
> 
> Since Im not that inclined in web dev yet, I guess you have the cue on this one so we leave the decision to you @larongbingo . Hows that sound @BernabePosadas?

okie. not also inclined to web yet.

**Comment by larongbingo** [comment]
Which meant using .Net stack since that's the tech stack, both of you are familiar. C# will be used then.

**Comment by larongbingo** [comment]
@team-noob-noob/team-noob-noob

**Comment by Joshykun** [comment]
Would it be better to try the reactive frameworks now? It could be beneficial to all of us

**Comment by joshybara** [comment]
Would it be better to try the reactive frameworks now? It could be beneficial to all of us


PS. Seriously I learned a lot of things just by making this repo @larongbingo so thnx a lot m8. I
researched a lot ahead so somehow now I could pick up some of the terms you say that I didnt came up with in class lol.

**Comment by larongbingo** [comment]
RX frameworks have steeper learning curves, but since they are addons, we can consider adding them to the project. So for .Net, we would use Rx .Net

Rx is said to be similar to event handling on UIs

**Comment by larongbingo** [comment]
Also we are not done with the language discussion since we still need to talk about the web part of the project. What will we use? ASP.NET or a separate UI framework?

**Comment by joshybara** [comment]
Im all up for ASP.NET unless you guys have a separate UI framework in mind

**Comment by larongbingo** [comment]
The question now is what will we use, .Net Framework or .Net Core?

**Comment by joshybara** [comment]
Since were doing this for a purpose and practice at the same time. I think its ideal to use now the .Net Core because that's where .NET framework is heading to anyway. 

So should we sail with the ASP.NET Core?

**Comment by larongbingo** [comment]
Alright, to sum things up.

We would be using .Net Core for the project with possible usage of other libs.

For the matter of the UI, we will be using the ASP.NET default, which is mainly HTML, CSS and JS.

**Comment by larongbingo** [comment]
@team-noob-noob/team-noob-noob
