### ISSUE TITLE
Design Architecture 

### ISSUE THREAD

**Issue by BernabePosadas** [team-noob-noob/libman#13]
What architecture we gonna use? MVC or other design architecture? 
- [x] MVC 
- [ ] Other

**Comment by larongbingo** [comment]
Once we cleared up this issue (#12) is finished, we can begin discussions on architecture and db.

**Comment by larongbingo** [comment]
@team-noob-noob/team-noob-noob 

Since we just finished #12, we can now begin discussions to architecture.

**Comment by joshybara** [comment]
I think MVC is still the good way to go

**Comment by larongbingo** [comment]
Closing the issue since we will be using MVC on ASP.NET
