### ISSUE TITLE
Audit Trail

### ISSUE THREAD

**Issue by El2829** [team-noob-noob/libman#5]
# Describe the Problem
Feature Request:  Audit Trial

- Provides the user with log-in / log-out and restricts all unauthorized person. If the user login all its transaction is recorded including entity username, date and time last log-in / log-out.

# Is this a bug or a new feature?
[] Bug
[*] Feature

**Comment by BernabePosadas** [comment]
User Level ba to?

**Comment by larongbingo** [comment]
Audit Trial or Audit Trail?

**Comment by larongbingo** [comment]
Given na ung Audit Trail sa #1 ni @BernabePosadas, gawa ka bago.

**Comment by larongbingo** [comment]
Reopened, "Yeaahh but in making a features/documentation seperated sya sa file maintenance"

**Comment by BernabePosadas** [comment]
> Reopened, "Yeaahh but in making a features/documentation seperated sya sa file maintenance"

But Audit trail is part of reports already. Bale duplicate eto boi
